add x-state and reanimated
TechnocultureResearch/MeWay pull request #11
Opened 2022-12-02 18:37 UTC by NamanRajputXXI

- [x] add x-state in Meway-table
- [x] Make minimal ui

2023-01-23 19:34 UTC, sutyum requested changes
need to remove `.idea` directory.

2023-01-23 19:34 UTC, sutyum commented on apps/meway-tablet/src/components/GlobalState.tsx
> +// import React, { createContext } from "react";
Remove this file if it is not needed

2023-01-23 19:34 UTC, sutyum commented on apps/meway-tablet/src/machines/navigationMachine.typegen.ts
> +// // This file was automatically generated. Edits will be overwritten
remove if not needed

2023-01-24 14:00 UTC, NamanRajputXXI commented on apps/meway-tablet/src/machines/navigationMachine.typegen.ts
> +// // This file was automatically generated. Edits will be overwritten
removed

2023-01-24 14:00 UTC, NamanRajputXXI commented on apps/meway-tablet/src/components/GlobalState.tsx
> +// import React, { createContext } from "react";
Removed

2023-01-24 15:37 UTC, sutyum approved these changes

2023-01-24 15:37 UTC, merged