Expo build issue
TechnocultureResearch/MeWay pull request #15
Opened 2022-12-12 22:03 UTC by chandantiwari1

made some changes in the repo to avoid eas  build errors

2022-12-13 13:49 UTC, sutyum commented
Issue with yarn workspace resolved? If so, describe how and merge conflicts to proceed to merge @chandantiwari1

2022-12-14 13:27 UTC, chandantiwari1 commented
> Issue with yarn workspace resolved? If so, describe how and merge conflicts to proceed to merge @chandantiwari1

yes issue with the yarn workspace has been. I delete  app.json, eas.json, tsconfig.json and these files are no longer needed. files which were in the root directory of our app 
reference: [pnpm monorepo](https://github.com/byCedric/expo-monorepo-example)
chan

2022-12-14 13:43 UTC, sutyum requested changes

2022-12-14 13:43 UTC, sutyum commented on apps/meway-tablet/package.json
> +  "main": "index.js",
why

2022-12-14 13:43 UTC, sutyum commented on apps/meway-tablet/src/constants/Colors.ts
> +const tintColor = "#4630ec";
use tailwind

2022-12-14 13:43 UTC, sutyum commented on apps/meway-tablet/src/screens/FaceCount.tsx
> +const styles = StyleSheet.create({
use tailwind/nativewind

2022-12-14 13:43 UTC, sutyum commented on apps/meway-tablet/tsconfig.json
> +  "include": ["./src/**/*","index.js"],
why

2022-12-14 13:43 UTC, sutyum commented on package.json
> -    "workspaces": [
How will packages be linked without this?

2022-12-14 13:48 UTC, chandantiwari1 commented on apps/meway-tablet/package.json
> +  "main": "index.js",
sir we can use any of then either ts or js . it doesn't affect the build process.

2022-12-14 13:48 UTC, chandantiwari1 commented on apps/meway-tablet/src/constants/Colors.ts
> +const tintColor = "#4630ec";
ok sir

2022-12-14 13:49 UTC, chandantiwari1 commented on apps/meway-tablet/src/screens/FaceCount.tsx
> +const styles = StyleSheet.create({
ok sir

2022-12-14 13:49 UTC, chandantiwari1 commented on apps/meway-tablet/tsconfig.json
> +  "include": ["./src/**/*","index.js"],
sir we can use any of then either ts or js . it doesn't affect the build process.

2022-12-14 13:52 UTC, chandantiwari1 commented on package.json
> -    "workspaces": [
sir i arranged them same as turbo repo docs, i didn't remove them.

2022-12-14 17:53 UTC, sutyum approved these changes

2022-12-14 17:53 UTC, merged