Create Python Script to download, extract YouTube videos and upload it to S3.
TechnocultureResearch/MeWay pull request #6
Opened 2022-11-15 14:56 UTC by AjayRangarajan

- Add functions to download, extract and upload videos to S3.
- Removed multi threading from the script since it caused **RuntimeError** when tried to upload video to S3.
- Will add multi threading in the next commit.

2022-11-15 17:00 UTC, sutyum requested changes
The commit is over all quite a good first commit. While various changes suggested are a matter of style, there is one key fundamental problem.

the flow of script should broadly follow the following procedure:
- open csv file
- parse the the csv file. if there are any issue with the format, throw reasonable errors. the output of this step should be a well constucted python object (Read: [Parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/)
- carry out downloads (show progress bars while the user waits: CLIs should never seem like they are stuck)
- create subclips (progress bar needed?) [what happens when the timestamp is outside the range of the length of the video?]
- upload (progress bar needed?)
- Report: Number of clips downloaded, number of subclass created, number of subclass uploaded, number of subclass failed to create or upload etc

2022-11-15 17:00 UTC, sutyum commented on scripts/README.md
> +Using venv:
not needed

2022-11-15 17:00 UTC, sutyum commented on scripts/requirements.txt
> +boto3==1.26.8
this file is not needed

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +
better to move everything in the script portion inside an if main block:
```python
if __name__ == '__main__':
  ...
```

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +        video_url (str): The URL of the Youtube Video
would be better to add type annotation to the function signature too

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +    vid = yt.streams.get_by_itag(22)
what does `22` signify here?

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +parser.add_argument('video_list', help='Video list location')
do you think click maybe a"nicer" option here?

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +    downloaded_video_path = vid.download(DOWNLOAD_PATH)
would be nice to see a progress bar for this process. Would it be useful to use `tqdm`?

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +    start_min, start_sec, end_min, end_sec = map(int, re.split('[:-]', timestamp))
you should do some checks here to ensure that the entire csv file is valid, and return reasonable errors if the csv file does not have the expected format

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +    start_min, start_sec, end_min, end_sec = map(int, re.split('[:-]', timestamp))
You could potentially use pydantic for validating the format of all the timestamps

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +def upload_to_s3(file_location, target_filename):
dead code?

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +    try:
this function is an empty abstraction, why do you need this?

2022-11-15 17:00 UTC, sutyum commented on scripts/script.py
> +with open(VIDEO_LIST, mode ='r')as file:
script bits should be in main block

2022-11-17 08:50 UTC, sutyum commented on scripts/script.py
> +        csvFile = csv.reader(file)
what if this file doesn't exist?

2022-11-17 08:51 UTC, sutyum commented on scripts/script.py
> +        os.mkdir(download_folder)
this may fail: if this fails: no need to do anything

2022-11-17 08:53 UTC, sutyum commented on scripts/script.py
> +            timestamps = row[1].split(';')
parsing all over the codebase

2022-11-18 18:05 UTC, sutyum commented
You need to resolve the conversations to proceed on this PR

2022-11-19 08:39 UTC, AjayRangarajan commented on scripts/README.md
> +Using venv:
Removed in the latest commit

2022-11-19 08:39 UTC, AjayRangarajan commented on scripts/requirements.txt
> +boto3==1.26.8
Removed and added Pipfile in the next commit

2022-11-19 08:40 UTC, AjayRangarajan commented on scripts/script.py
> +
Moved the code to the if block as mentioned.

2022-11-19 08:40 UTC, AjayRangarajan commented on scripts/script.py
> +        video_url (str): The URL of the Youtube Video
Add type annotations in the next commit

2022-11-19 08:43 UTC, AjayRangarajan commented on scripts/script.py
> +    downloaded_video_path = vid.download(DOWNLOAD_PATH)
Individual progress bar is not showing up when downloading videos in multi thread. When downloading as Thread pools, a single progress bar appears for the complete download process.

2022-11-19 08:45 UTC, AjayRangarajan commented on scripts/script.py
> +    start_min, start_sec, end_min, end_sec = map(int, re.split('[:-]', timestamp))
Implemented custom validator for parsing the csv file and validating.

2022-11-19 08:45 UTC, AjayRangarajan commented on scripts/script.py
> +def upload_to_s3(file_location, target_filename):
Removed in the next commit.

2022-11-19 08:46 UTC, AjayRangarajan commented on scripts/script.py
> +    try:
Removed in the next commit

2022-11-19 08:46 UTC, AjayRangarajan commented on scripts/script.py
> +with open(VIDEO_LIST, mode ='r')as file:
Moved to the main block as mentioned.

2022-11-19 08:47 UTC, AjayRangarajan commented on scripts/script.py
> +        csvFile = csv.reader(file)
Added a condition to check if the file exists in the next commit.

2022-11-19 08:48 UTC, AjayRangarajan commented on scripts/script.py
> +            timestamps = row[1].split(';')
Created a custom validator which will parse the file and take care of all validation. Which will also return a pydantic object that will be used in the download and extract functions.

2022-11-19 09:41 UTC, sutyum requested changes

2022-11-19 09:41 UTC, sutyum commented on scripts/.gitignore
> +# references
move the folder into a subdirectory of scripts named aptly: scripts/s3_uploader_cli/

2022-11-19 09:41 UTC, sutyum commented on scripts/README.md
> +python script.py <video_list.csv> <s3_bucket_name>
```
piping shell
python ...
```

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +                raise Exception(f"The csv file {self.video_list} is empty!")
`ValueError()`

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +                raise Exception(f"The csv file {self.video_list} is empty!")
```
class EmptyCsvFileError(Exception):
  pass
```

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +class TimeStamp(BaseModel):
the validator for timestamps would go here

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +class VideoDetail(BaseModel):
validator for url would go here

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +            csvList = list(enumerate(csvFile))
`video_list = VideoList(list(enumerate(csvfile)))` --> python object with a the data. The key point is that all our data in this object are guaranteed to be in the correct format.

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +    entry: List[VideoDetail]
can line count validation go in here or it has to be in the parse function?

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +    except Exception as e:
you only need to catch exception if you are going to act on it. If it is an error that will be propagated to the CLI user, no need to catch

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +    except Exception as e:
`except Exception as e:` -> this is a major anti pattern

2022-11-19 09:41 UTC, sutyum commented on scripts/script.py
> +    filename = tail[0:-5]
why this needed?

2022-11-23 07:34 UTC, sutyum approved these changes

2022-11-23 07:35 UTC, sutyum approved these changes

2022-11-23 07:36 UTC, sutyum approved these changes

2022-11-23 07:37 UTC, merged