Git hubwork flows build
TechnocultureResearch/MeWay pull request #7
Opened 2022-11-19 09:32 UTC by chandantiwari1

add build in the workflows

2022-11-19 09:44 UTC, sutyum requested changes

2022-11-19 09:44 UTC, sutyum commented on apps/web/package.json
> +    "@meway/api": "file:../../packages/api",
why is this needed?

2022-11-19 09:44 UTC, sutyum commented on apps/web/package.json
> +    "react-native": "0.69.6"
why is this needed?

2022-11-19 09:44 UTC, sutyum commented on apps/web/package.json
> +    "react": "18.0.0",
why is this needed?

2022-11-19 09:44 UTC, sutyum commented on apps/meway-tablet/src/_app.tsx
> +import "react-native-get-random-values";
why is this needed?

2022-11-19 09:44 UTC, sutyum commented on apps/meway-tablet/package.json
> +    "@meway/api": "file:../../packages/api",
why?

2022-11-19 09:44 UTC, sutyum commented on apps/meway-tablet/package.json
> -    "dev": "expo start --android",
why?

2022-11-22 09:54 UTC, chandantiwari1 commented on apps/web/package.json
> +    "@meway/api": "file:../../packages/api",
sir yarn workspace error, so i converted pnpm packages to the yarn

2022-11-22 09:55 UTC, chandantiwari1 commented on apps/web/package.json
> +    "react-native": "0.69.6"
react-native peer dependencies error so that I deprecetated it to 9.69.6

2022-11-22 09:56 UTC, chandantiwari1 commented on apps/web/package.json
> +    "react": "18.0.0",
peer dependencies error

2022-11-22 09:57 UTC, chandantiwari1 commented on apps/meway-tablet/src/_app.tsx
> +import "react-native-get-random-values";
to uuid random values error

2022-11-22 09:57 UTC, chandantiwari1 commented on apps/meway-tablet/package.json
> +    "@meway/api": "file:../../packages/api",
yarn workspaces error

2022-11-22 09:58 UTC, chandantiwari1 commented on apps/meway-tablet/package.json
> -    "dev": "expo start --android",
I will fix this in the next commit.

2022-12-01 12:59 UTC, closed without merging